language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0.0"
  - "iojs-v2.0.0"
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
